version: '1.0'
services:
  orderTable:
    image: watierapi:waiter-latest
    environment:
      - SPRING_LIQUIBASE_ENABLED=true
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    environment:
        POSTGRES_DB: mydb
        POSTGRES_USER: atimo
        POSTGRES_PASSWORD: atimopw
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - D:/PostgresData:/var/lib/postgresql/data
