version: '1.0'
services:
  orderTable:
    image: watierapi:waiter-latest
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    environment:
        POSTGRES_DB: mydb
        POSTGRES_USER: atimo
        POSTGRES_PASSWORD: atimopw
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - D:/PostgresData:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "6080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=atimopw
      - DB_VENDOR=postgres
      - DB_USER=atimo
      - DB_PASSWORD=atimopw
      - DB_ADDR=db
      - DB_DATABASE=mydb
      - DB_PORT=5432
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ${PWD}/realm-export:/tmp
    depends_on:
      - db